#! /bin/sh
# Script to bring a network (tap) device for qemu up.

# in order to be able to find brctl
PATH=$PATH:/sbin:/usr/sbin
ip=$(which ip)

if [ -n "$ip" ]; then
   ip link set "$1" up
else
   ifconfig "$1" 0.0.0.0 up
fi

